FISH-6285 Apply patches
payara/patched-src-jersey pull request #142
Opened 2022-07-25 15:26 UTC by kalinchan

2022-07-25 18:17 UTC, luiseufrasio requested changes, later dismissed

2022-07-25 18:17 UTC, luiseufrasio commented on ext/microprofile/mp-rest-client/src/main/java/org/glassfish/jersey/microprofile/restclient/InterfaceModel.java
>  import java.util.List;
update Copyright year

2022-07-25 18:17 UTC, luiseufrasio commented on tests/osgi/functional/src/test/java/org/glassfish/jersey/osgi/test/basic/ApacheOsgiIntegrationTest.java
> +//@RunWith(PaxExam.class)
This test will not be executed? Why?

2022-07-28 16:48 UTC, Pandrex247 reviewed
MicroProfile Rest Client TCK doesn't seem to be happy with this. Lots of NoClassDefFounds, can you double-check?
`java.lang.NoClassDefFoundError: org/glassfish/jersey/ext/cdi1x/internal/CdiUtil`

2022-08-17 10:49 UTC, Pandrex247 requested changes
Breaks jersey-tests-e2e

2022-08-22 14:07 UTC, breakponchito approved these changes
LGTM

2022-08-23 08:58 UTC, Pandrex247 reviewed
Running additional tests - I think one of our patches breaks something which passes on 2.36 vanilla.

2022-08-23 10:37 UTC, Pandrex247 requested changes
This breaks the osgi-functional tests.
They pass on both 2.36 vanilla and on 2.36 with the cherry-picked OSGi header fix from jansupol.

One of our previous patches breaks this test.

2022-08-23 11:04 UTC, kalinchan commented
I managed to successfully run all tests, all of them passed when I ran them.

2022-08-23 14:37 UTC, Pandrex247 commented
Oh you're right - I done goofed and checked out the wrong branch.

2022-08-23 14:37 UTC, Pandrex247 approved these changes

2022-08-23 14:38 UTC, Pandrex247 commented
Technically I don't think we actually need the additional changes on top of the microprofile.config.version change in https://github.com/payara/patched-src-jersey/pull/142/commits/c91eff607c334670e2e1bceeeb9473b8af79e41e but that shouldn't block for now.

2022-08-23 14:39 UTC, merged